"""add_token_type_to_change_tokens

Revision ID: e8468f7a6226
Revises: a4c4ca42cda7
Create Date: 2026-07-24 00:46:59.894232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8468f7a6226'
down_revision: Union[str, Sequence[str], None] = 'a4c4ca42cda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_tokens', sa.Column('token_type', sa.String(), nullable=False, comment='PASSWORD_RESET | EMAIL_CHANGE | PHONE_CHANGE | WALLET_CHANGE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_tokens', 'token_type')
    # ### end Alembic commands ###
